name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12.2']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run all tests
      run: |
        python -m unittest discover test -v
    
    - name: Run tests by module
      run: |
        python -m unittest discover test -k "test_chromosome" -v
        python -m unittest discover test -k "test_data_collector" -v
        python -m unittest discover test -k "test_portfolio" -v
        python -m unittest discover test -k "test_genetic_algorithm" -v